### ISSUE TITLE
Using tidal-stack with atom

### ISSUE THREAD

**Issue by foobar0112** [tonyday567/tidal-stack#1]
Hey, thanks to this wrapper I managed to install tidal over stack on Arch (which didn't work with cabal before…). Are there additional steps to use the resulting installation over the Atom-Plugin? Because when trying to boot tidal the following error is thrown (like as tidal wasn't installed at all):
```
: error:
    Could not find module ‘Sound.Tidal.Context’
    It is not a module in the current program, or in any known package.

[...]
```
As this created like an local installation (as far as I understood correctly) some link/include/load is missing, probably?

**Comment by tonyday567** [comment]
Awesome!  I don't have much experience with Atom, but it sounds like it's working generically.
